global:
  sequences_file: /mnt/fasta.fa
  prefix: /mnt/output
prottrans_t5_xl_u50_embeddings:
  type: embed
  protocol: prottrans_t5_xl_u50
  model_directory: /.cache/bio_embeddings/prottrans_t5_xl_u50/model_directory
  reduce: True
tsne_projections:
  type: project
  protocol: tsne
  depends_on: prottrans_t5_xl_u50_embeddings
plotly_visualization:
  type: visualize
  protocol: plotly
  depends_on: tsne_projections
  annotation_file: /mnt/annotation_file.csv
